version: '3.3'

services:
  vr_postgres:
    build:
      context: ./service
      dockerfile: Dockerfile
    volumes:
      - './service:/usr/src/app'
    ports:
      - 5000:5001
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - SECRET_KEY=my_precious